### ISSUE TITLE
not an issue just a question!

### ISSUE THREAD

**Issue by tryuut89** [MarcusNg/flutter_notion_budget#1]
hi! this is probably a very basic, annoying question but since you have the code here, is there a way for me to just apply it and get the tracker without doing the code myself? I know nothing about coding but I loved your video and the outcome, just wondering how I apply the things in the MACOS folder to my mac and how I get it running if it's possible, LMK!

**Comment by bgwastu** [comment]
Do you mean compile it into application? If you using Android you can [follow this guide](https://www.youtube.com/watch?v=qSn68_WLRKc), or [here](https://www.youtube.com/watch?v=1Ak6h1wGPO4) if you're IOS user.
Just don't forget to create the .env file and add your database id and notion token there

**Comment by dawl1** [comment]
Thank you!

**Comment by tryuut89** [comment]
Thank you!
